### ISSUE TITLE
Plugin not in WP repo?

### ISSUE THREAD

**Issue by uhlhosting** [KamataRyo/inherit-theme-mods#1]
I cannot find the plugin in Wordpress repo anymore.

**Comment by kamataryo** [comment]
Hi, in my case I can still find it.
Try to check it from web "https://wordpress.org/plugins/inherit-theme-mods/"
or, from your WordPress site, like "http://{{yourhost}}/wp-admin/plugin-install.php?tab=search&s=inherit+theme+mods".

**Comment by kamataryo** [comment]
Or search it with words like "inherit theme mods" at "https://{{yourhost}}/wp-admin/plugin-install.php".

**Comment by uhlhosting** [comment]
Yes i can find it now, maybe was some temporary issue. I do have one more issue, I have this in settings: https://www.dropbox.com/s/kvt5o4igf262yby/Screenshot%202016-08-10%2013.41.37.png?dl=0 is a bit different form the interface you showcased on your site... Any idea why?

**Comment by kamataryo** [comment]
I'm glad to hear that :)

And for the other issue, yes, the UI at the latest version(2.1.0) is different from the images on showcase. thank you for letting me know it.
At [the update to v2.0.0](https://github.com/KamataRyo/inherit-theme-mods/releases/tag/v2.0.0) I removed graphical icons but you can still see it at [the showcase](https://wordpress.org/plugins/inherit-theme-mods/screenshots/). This is only because I had a lot on my plate and I didn't replace it.
For the reason, I was a little bit confused about licenses of my plugin (GPL) and the icon library (font-awesome). I was not sure whether I can use it at the moment of the update, but I am sure now that it's OK. So it's ready to restore the UI with icons on next update.
The remaining difficult is which is easier to understand, with or without icons. I am not sure whether the icons help users to understand how does this plugin work and someone perhaps think it's too complex.

which do you think is easier to understand?
![2016-08-10 21 24 12](https://cloud.githubusercontent.com/assets/6292312/17553499/0e17a610-5f41-11e6-90c2-02622fd89e22.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/6292312/17553498/0e178ef0-5f41-11e6-802a-e00f58045160.png)

**Comment by uhlhosting** [comment]
just add a small legend explaining what each icon represents.  i think with the icons and desc is just great.

**Comment by uhlhosting** [comment]
btw amazing plugin, guess i had first installs :)

**Comment by kamataryo** [comment]
Thank you for the feedback!
Next update is going to contain UI restore :)
